### ISSUE TITLE
Missing 'explanations' path?

### ISSUE THREAD

**Issue by reachsumit** [Tigxy/SiBraR---Single-Branch-Recommender#1]
Hello!

Thank you for publishing your fantastic work.

At https://github.com/Tigxy/SiBraR---Single-Branch-Recommender/blob/main/algorithms/sgd_alg.py#L21 you seem to be importing from 'explanations', but that path doesn't seem to exist, and isn't a part of the conda environment. Is this some missing package?

Also, curious to know what was your hypothesis for sampling modalities instead of using all available ones at training time.

Thanks again!

**Comment by Tigxy** [comment]
Hi there!

Thanks for your interest in our work! 

Ohh right, sorry about that! Unfortunately, I was too eager in cleaning up the repo and deleted this part of our code for the publication -- I will fix this next week! For now, as we don't use the imported functions in SiBraR, please just uncomment the respective import statement.

That's a good question! One of the main motivations was that it reduces the complexity of the regularization term, since InfoNCE is computed between pairs of modalities. Thus, if we would use all modalities per item during training, we'd have to compute the loss between all possible pairs (e.g., for 5 modalities there are 10 pairs). 
For future research, it might be worth checking out how this effects the speed of convergence (and at which local minima we arrive).
